// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcahfnjgcwgntwkwypvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjYWhmbmpnY3dnbnR3a3d5cHZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MjE3MjcsImV4cCI6MjA2NzI5NzcyN30.2Hv3YpPtRQ8jKDrEWmumNU_VWyA-Zeytf-lGty1uBKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});